apiVersion: v1
kind: Pod
metadata:
  name: fastingress
  labels:
    app.kubernetes.io/name: proxy
spec:
  containers:
  - name: fastingress
    image: fastingress:latest
    imagePullPolicy: Never
    ports:
      - containerPort: 3000
        name: ingress-port

---
apiVersion: v1
kind: Service
metadata:
  name: ingress-service
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 3000
    targetPort: ingress-port