apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress-configuration3
spec:
  ingressClassName: fastingress
  rules:
    - http:
        paths:
          - path: /baaas
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
